# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Sara Ekholm – Planner in advertising, branding and digital"
description: > # this means to ignore newlines until "baseurl:"
  I’m a planner from Sweden equipped to tackle the modern media landscape. Fluent in Advertising, Branding, and Digital. Also a strong advocate of common sense.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://saraekholm.se" # the base hostname & protocol for your site
permalink: /blog/:title
# Build settings
markdown: kramdown
include: ['_pages']